%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.3.1

-ifndef(gogo_pb).
-define(gogo_pb, true).

-define(gogo_pb_gpb_version, "4.3.1").

-ifndef('GOOGLE.PROTOBUF.FILEDESCRIPTORSET_PB_H').
-define('GOOGLE.PROTOBUF.FILEDESCRIPTORSET_PB_H', true).
-record('google.protobuf.FileDescriptorSet',
        {file = []              :: [gogo_pb:'google.protobuf.FileDescriptorProto'()] | undefined % = 1
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.FILEDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.FILEDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.FileDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         package                :: iodata() | undefined, % = 2
         dependency = []        :: [iodata()] | undefined, % = 3
         public_dependency = [] :: [integer()] | undefined, % = 10, 32 bits
         weak_dependency = []   :: [integer()] | undefined, % = 11, 32 bits
         message_type = []      :: [gogo_pb:'google.protobuf.DescriptorProto'()] | undefined, % = 4
         enum_type = []         :: [gogo_pb:'google.protobuf.EnumDescriptorProto'()] | undefined, % = 5
         service = []           :: [gogo_pb:'google.protobuf.ServiceDescriptorProto'()] | undefined, % = 6
         extension = []         :: [gogo_pb:'google.protobuf.FieldDescriptorProto'()] | undefined, % = 7
         options                :: gogo_pb:'google.protobuf.FileOptions'() | undefined, % = 8
         source_code_info       :: gogo_pb:'google.protobuf.SourceCodeInfo'() | undefined, % = 9
         syntax                 :: iodata() | undefined % = 12
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.DESCRIPTORPROTO.EXTENSIONRANGE_PB_H').
-define('GOOGLE.PROTOBUF.DESCRIPTORPROTO.EXTENSIONRANGE_PB_H', true).
-record('google.protobuf.DescriptorProto.ExtensionRange',
        {start                  :: integer() | undefined, % = 1, 32 bits
         'end'                  :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.DESCRIPTORPROTO.RESERVEDRANGE_PB_H').
-define('GOOGLE.PROTOBUF.DESCRIPTORPROTO.RESERVEDRANGE_PB_H', true).
-record('google.protobuf.DescriptorProto.ReservedRange',
        {start                  :: integer() | undefined, % = 1, 32 bits
         'end'                  :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.DESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.DESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.DescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         field = []             :: [gogo_pb:'google.protobuf.FieldDescriptorProto'()] | undefined, % = 2
         extension = []         :: [gogo_pb:'google.protobuf.FieldDescriptorProto'()] | undefined, % = 6
         nested_type = []       :: [gogo_pb:'google.protobuf.DescriptorProto'()] | undefined, % = 3
         enum_type = []         :: [gogo_pb:'google.protobuf.EnumDescriptorProto'()] | undefined, % = 4
         extension_range = []   :: [gogo_pb:'google.protobuf.DescriptorProto.ExtensionRange'()] | undefined, % = 5
         oneof_decl = []        :: [gogo_pb:'google.protobuf.OneofDescriptorProto'()] | undefined, % = 8
         options                :: gogo_pb:'google.protobuf.MessageOptions'() | undefined, % = 7
         reserved_range = []    :: [gogo_pb:'google.protobuf.DescriptorProto.ReservedRange'()] | undefined, % = 9
         reserved_name = []     :: [iodata()] | undefined % = 10
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.FIELDDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.FIELDDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.FieldDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         number                 :: integer() | undefined, % = 3, 32 bits
         label                  :: 'LABEL_OPTIONAL' | 'LABEL_REQUIRED' | 'LABEL_REPEATED' | integer() | undefined, % = 4, enum google.protobuf.FieldDescriptorProto.Label
         type                   :: 'TYPE_DOUBLE' | 'TYPE_FLOAT' | 'TYPE_INT64' | 'TYPE_UINT64' | 'TYPE_INT32' | 'TYPE_FIXED64' | 'TYPE_FIXED32' | 'TYPE_BOOL' | 'TYPE_STRING' | 'TYPE_GROUP' | 'TYPE_MESSAGE' | 'TYPE_BYTES' | 'TYPE_UINT32' | 'TYPE_ENUM' | 'TYPE_SFIXED32' | 'TYPE_SFIXED64' | 'TYPE_SINT32' | 'TYPE_SINT64' | integer() | undefined, % = 5, enum google.protobuf.FieldDescriptorProto.Type
         type_name              :: iodata() | undefined, % = 6
         extendee               :: iodata() | undefined, % = 2
         default_value          :: iodata() | undefined, % = 7
         oneof_index            :: integer() | undefined, % = 9, 32 bits
         json_name              :: iodata() | undefined, % = 10
         options                :: gogo_pb:'google.protobuf.FieldOptions'() | undefined % = 8
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ONEOFDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.ONEOFDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.OneofDescriptorProto',
        {name                   :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ENUMDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.ENUMDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.EnumDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         value = []             :: [gogo_pb:'google.protobuf.EnumValueDescriptorProto'()] | undefined, % = 2
         options                :: gogo_pb:'google.protobuf.EnumOptions'() | undefined % = 3
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ENUMVALUEDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.ENUMVALUEDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.EnumValueDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         number                 :: integer() | undefined, % = 2, 32 bits
         options                :: gogo_pb:'google.protobuf.EnumValueOptions'() | undefined % = 3
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.SERVICEDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.SERVICEDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.ServiceDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         method = []            :: [gogo_pb:'google.protobuf.MethodDescriptorProto'()] | undefined, % = 2
         options                :: gogo_pb:'google.protobuf.ServiceOptions'() | undefined % = 3
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.METHODDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.METHODDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.MethodDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         input_type             :: iodata() | undefined, % = 2
         output_type            :: iodata() | undefined, % = 3
         options                :: gogo_pb:'google.protobuf.MethodOptions'() | undefined, % = 4
         client_streaming = false :: boolean() | 0 | 1 | undefined, % = 5
         server_streaming = false :: boolean() | 0 | 1 | undefined % = 6
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.FILEOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.FILEOPTIONS_PB_H', true).
-record('google.protobuf.FileOptions',
        {java_package           :: iodata() | undefined, % = 1
         java_outer_classname   :: iodata() | undefined, % = 8
         java_multiple_files = false :: boolean() | 0 | 1 | undefined, % = 10
         java_generate_equals_and_hash = false :: boolean() | 0 | 1 | undefined, % = 20
         java_string_check_utf8 = false :: boolean() | 0 | 1 | undefined, % = 27
         optimize_for = 'SPEED' :: 'SPEED' | 'CODE_SIZE' | 'LITE_RUNTIME' | integer() | undefined, % = 9, enum google.protobuf.FileOptions.OptimizeMode
         go_package             :: iodata() | undefined, % = 11
         cc_generic_services = false :: boolean() | 0 | 1 | undefined, % = 16
         java_generic_services = false :: boolean() | 0 | 1 | undefined, % = 17
         py_generic_services = false :: boolean() | 0 | 1 | undefined, % = 18
         deprecated = false     :: boolean() | 0 | 1 | undefined, % = 23
         cc_enable_arenas = false :: boolean() | 0 | 1 | undefined, % = 31
         objc_class_prefix      :: iodata() | undefined, % = 36
         csharp_namespace       :: iodata() | undefined, % = 37
         javanano_use_deprecated_package :: boolean() | 0 | 1 | undefined, % = 38
         uninterpreted_option = [] :: [gogo_pb:'google.protobuf.UninterpretedOption'()] | undefined, % = 999
         goproto_getters_all    :: boolean() | 0 | 1 | undefined, % = 63001
         goproto_enum_prefix_all :: boolean() | 0 | 1 | undefined, % = 63002
         goproto_stringer_all   :: boolean() | 0 | 1 | undefined, % = 63003
         verbose_equal_all      :: boolean() | 0 | 1 | undefined, % = 63004
         face_all               :: boolean() | 0 | 1 | undefined, % = 63005
         gostring_all           :: boolean() | 0 | 1 | undefined, % = 63006
         populate_all           :: boolean() | 0 | 1 | undefined, % = 63007
         stringer_all           :: boolean() | 0 | 1 | undefined, % = 63008
         onlyone_all            :: boolean() | 0 | 1 | undefined, % = 63009
         equal_all              :: boolean() | 0 | 1 | undefined, % = 63013
         description_all        :: boolean() | 0 | 1 | undefined, % = 63014
         testgen_all            :: boolean() | 0 | 1 | undefined, % = 63015
         benchgen_all           :: boolean() | 0 | 1 | undefined, % = 63016
         marshaler_all          :: boolean() | 0 | 1 | undefined, % = 63017
         unmarshaler_all        :: boolean() | 0 | 1 | undefined, % = 63018
         stable_marshaler_all   :: boolean() | 0 | 1 | undefined, % = 63019
         sizer_all              :: boolean() | 0 | 1 | undefined, % = 63020
         goproto_enum_stringer_all :: boolean() | 0 | 1 | undefined, % = 63021
         enum_stringer_all      :: boolean() | 0 | 1 | undefined, % = 63022
         unsafe_marshaler_all   :: boolean() | 0 | 1 | undefined, % = 63023
         unsafe_unmarshaler_all :: boolean() | 0 | 1 | undefined, % = 63024
         goproto_extensions_map_all :: boolean() | 0 | 1 | undefined, % = 63025
         goproto_unrecognized_all :: boolean() | 0 | 1 | undefined, % = 63026
         gogoproto_import       :: boolean() | 0 | 1 | undefined, % = 63027
         protosizer_all         :: boolean() | 0 | 1 | undefined, % = 63028
         compare_all            :: boolean() | 0 | 1 | undefined % = 63029
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.MESSAGEOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.MESSAGEOPTIONS_PB_H', true).
-record('google.protobuf.MessageOptions',
        {message_set_wire_format = false :: boolean() | 0 | 1 | undefined, % = 1
         no_standard_descriptor_accessor = false :: boolean() | 0 | 1 | undefined, % = 2
         deprecated = false     :: boolean() | 0 | 1 | undefined, % = 3
         map_entry              :: boolean() | 0 | 1 | undefined, % = 7
         uninterpreted_option = [] :: [gogo_pb:'google.protobuf.UninterpretedOption'()] | undefined, % = 999
         goproto_getters        :: boolean() | 0 | 1 | undefined, % = 64001
         goproto_stringer       :: boolean() | 0 | 1 | undefined, % = 64003
         verbose_equal          :: boolean() | 0 | 1 | undefined, % = 64004
         face                   :: boolean() | 0 | 1 | undefined, % = 64005
         gostring               :: boolean() | 0 | 1 | undefined, % = 64006
         populate               :: boolean() | 0 | 1 | undefined, % = 64007
         stringer               :: boolean() | 0 | 1 | undefined, % = 67008
         onlyone                :: boolean() | 0 | 1 | undefined, % = 64009
         equal                  :: boolean() | 0 | 1 | undefined, % = 64013
         description            :: boolean() | 0 | 1 | undefined, % = 64014
         testgen                :: boolean() | 0 | 1 | undefined, % = 64015
         benchgen               :: boolean() | 0 | 1 | undefined, % = 64016
         marshaler              :: boolean() | 0 | 1 | undefined, % = 64017
         unmarshaler            :: boolean() | 0 | 1 | undefined, % = 64018
         stable_marshaler       :: boolean() | 0 | 1 | undefined, % = 64019
         sizer                  :: boolean() | 0 | 1 | undefined, % = 64020
         unsafe_marshaler       :: boolean() | 0 | 1 | undefined, % = 64023
         unsafe_unmarshaler     :: boolean() | 0 | 1 | undefined, % = 64024
         goproto_extensions_map :: boolean() | 0 | 1 | undefined, % = 64025
         goproto_unrecognized   :: boolean() | 0 | 1 | undefined, % = 64026
         protosizer             :: boolean() | 0 | 1 | undefined, % = 64028
         compare                :: boolean() | 0 | 1 | undefined % = 64029
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.FIELDOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.FIELDOPTIONS_PB_H', true).
-record('google.protobuf.FieldOptions',
        {ctype = 'STRING'       :: 'STRING' | 'CORD' | 'STRING_PIECE' | integer() | undefined, % = 1, enum google.protobuf.FieldOptions.CType
         packed                 :: boolean() | 0 | 1 | undefined, % = 2
         jstype = 'JS_NORMAL'   :: 'JS_NORMAL' | 'JS_STRING' | 'JS_NUMBER' | integer() | undefined, % = 6, enum google.protobuf.FieldOptions.JSType
         lazy = false           :: boolean() | 0 | 1 | undefined, % = 5
         deprecated = false     :: boolean() | 0 | 1 | undefined, % = 3
         weak = false           :: boolean() | 0 | 1 | undefined, % = 10
         uninterpreted_option = [] :: [gogo_pb:'google.protobuf.UninterpretedOption'()] | undefined, % = 999
         nullable               :: boolean() | 0 | 1 | undefined, % = 65001
         embed                  :: boolean() | 0 | 1 | undefined, % = 65002
         customtype             :: iodata() | undefined, % = 65003
         customname             :: iodata() | undefined, % = 65004
         jsontag                :: iodata() | undefined, % = 65005
         moretags               :: iodata() | undefined, % = 65006
         casttype               :: iodata() | undefined, % = 65007
         castkey                :: iodata() | undefined, % = 65008
         castvalue              :: iodata() | undefined, % = 65009
         stdtime                :: boolean() | 0 | 1 | undefined, % = 65010
         stdduration            :: boolean() | 0 | 1 | undefined % = 65011
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ENUMOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.ENUMOPTIONS_PB_H', true).
-record('google.protobuf.EnumOptions',
        {allow_alias            :: boolean() | 0 | 1 | undefined, % = 2
         deprecated = false     :: boolean() | 0 | 1 | undefined, % = 3
         uninterpreted_option = [] :: [gogo_pb:'google.protobuf.UninterpretedOption'()] | undefined, % = 999
         goproto_enum_prefix    :: boolean() | 0 | 1 | undefined, % = 62001
         goproto_enum_stringer  :: boolean() | 0 | 1 | undefined, % = 62021
         enum_stringer          :: boolean() | 0 | 1 | undefined, % = 62022
         enum_customname        :: iodata() | undefined % = 62023
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ENUMVALUEOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.ENUMVALUEOPTIONS_PB_H', true).
-record('google.protobuf.EnumValueOptions',
        {deprecated = false     :: boolean() | 0 | 1 | undefined, % = 1
         uninterpreted_option = [] :: [gogo_pb:'google.protobuf.UninterpretedOption'()] | undefined, % = 999
         enumvalue_customname   :: iodata() | undefined % = 66001
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.SERVICEOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.SERVICEOPTIONS_PB_H', true).
-record('google.protobuf.ServiceOptions',
        {deprecated = false     :: boolean() | 0 | 1 | undefined, % = 33
         uninterpreted_option = [] :: [gogo_pb:'google.protobuf.UninterpretedOption'()] | undefined % = 999
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.METHODOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.METHODOPTIONS_PB_H', true).
-record('google.protobuf.MethodOptions',
        {deprecated = false     :: boolean() | 0 | 1 | undefined, % = 33
         uninterpreted_option = [] :: [gogo_pb:'google.protobuf.UninterpretedOption'()] | undefined % = 999
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.UNINTERPRETEDOPTION.NAMEPART_PB_H').
-define('GOOGLE.PROTOBUF.UNINTERPRETEDOPTION.NAMEPART_PB_H', true).
-record('google.protobuf.UninterpretedOption.NamePart',
        {name_part              :: iodata(),        % = 1
         is_extension           :: boolean() | 0 | 1 % = 2
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.UNINTERPRETEDOPTION_PB_H').
-define('GOOGLE.PROTOBUF.UNINTERPRETEDOPTION_PB_H', true).
-record('google.protobuf.UninterpretedOption',
        {name = []              :: [gogo_pb:'google.protobuf.UninterpretedOption.NamePart'()] | undefined, % = 2
         identifier_value       :: iodata() | undefined, % = 3
         positive_int_value     :: non_neg_integer() | undefined, % = 4, 32 bits
         negative_int_value     :: integer() | undefined, % = 5, 32 bits
         double_value           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 6
         string_value           :: iodata() | undefined, % = 7
         aggregate_value        :: iodata() | undefined % = 8
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.SOURCECODEINFO.LOCATION_PB_H').
-define('GOOGLE.PROTOBUF.SOURCECODEINFO.LOCATION_PB_H', true).
-record('google.protobuf.SourceCodeInfo.Location',
        {path = []              :: [integer()] | undefined, % = 1, 32 bits
         span = []              :: [integer()] | undefined, % = 2, 32 bits
         leading_comments       :: iodata() | undefined, % = 3
         trailing_comments      :: iodata() | undefined, % = 4
         leading_detached_comments = [] :: [iodata()] | undefined % = 6
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.SOURCECODEINFO_PB_H').
-define('GOOGLE.PROTOBUF.SOURCECODEINFO_PB_H', true).
-record('google.protobuf.SourceCodeInfo',
        {location = []          :: [gogo_pb:'google.protobuf.SourceCodeInfo.Location'()] | undefined % = 1
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.GENERATEDCODEINFO.ANNOTATION_PB_H').
-define('GOOGLE.PROTOBUF.GENERATEDCODEINFO.ANNOTATION_PB_H', true).
-record('google.protobuf.GeneratedCodeInfo.Annotation',
        {path = []              :: [integer()] | undefined, % = 1, 32 bits
         source_file            :: iodata() | undefined, % = 2
         'begin'                :: integer() | undefined, % = 3, 32 bits
         'end'                  :: integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.GENERATEDCODEINFO_PB_H').
-define('GOOGLE.PROTOBUF.GENERATEDCODEINFO_PB_H', true).
-record('google.protobuf.GeneratedCodeInfo',
        {annotation = []        :: [gogo_pb:'google.protobuf.GeneratedCodeInfo.Annotation'()] | undefined % = 1
        }).
-endif.

-endif.
