%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.3.1

-ifndef(router_pb).
-define(router_pb, true).

-define(router_pb_gpb_version, "4.3.1").

-ifndef('ETCD.RESPONSEHEADER_PB_H').
-define('ETCD.RESPONSEHEADER_PB_H', true).
-record('Etcd.ResponseHeader',
        {cluster_id = 0         :: non_neg_integer() | undefined, % = 1, 32 bits
         member_id = 0          :: non_neg_integer() | undefined, % = 2, 32 bits
         revision = 0           :: integer() | undefined, % = 3, 32 bits
         raft_term = 0          :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('ETCD.RANGEREQUEST_PB_H').
-define('ETCD.RANGEREQUEST_PB_H', true).
-record('Etcd.RangeRequest',
        {key = <<>>             :: iodata() | undefined, % = 1
         range_end = <<>>       :: iodata() | undefined, % = 2
         limit = 0              :: integer() | undefined, % = 3, 32 bits
         revision = 0           :: integer() | undefined, % = 4, 32 bits
         sort_order = 'NONE'    :: 'NONE' | 'ASCEND' | 'DESCEND' | integer() | undefined, % = 5, enum Etcd.RangeRequest.SortOrder
         sort_target = 'KEY'    :: 'KEY' | 'VERSION' | 'CREATE' | 'MOD' | 'VALUE' | integer() | undefined, % = 6, enum Etcd.RangeRequest.SortTarget
         serializable = false   :: boolean() | 0 | 1 | undefined, % = 7
         keys_only = false      :: boolean() | 0 | 1 | undefined, % = 8
         count_only = false     :: boolean() | 0 | 1 | undefined, % = 9
         min_mod_revision = 0   :: integer() | undefined, % = 10, 32 bits
         max_mod_revision = 0   :: integer() | undefined, % = 11, 32 bits
         min_create_revision = 0 :: integer() | undefined, % = 12, 32 bits
         max_create_revision = 0 :: integer() | undefined % = 13, 32 bits
        }).
-endif.

-ifndef('ETCD.RANGERESPONSE_PB_H').
-define('ETCD.RANGERESPONSE_PB_H', true).
-record('Etcd.RangeResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         kvs = []               :: [router_pb:'mvccpb.KeyValue'()] | undefined, % = 2
         more = false           :: boolean() | 0 | 1 | undefined, % = 3
         count = 0              :: integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('ETCD.PUTREQUEST_PB_H').
-define('ETCD.PUTREQUEST_PB_H', true).
-record('Etcd.PutRequest',
        {key = <<>>             :: iodata() | undefined, % = 1
         value = <<>>           :: iodata() | undefined, % = 2
         lease = 0              :: integer() | undefined, % = 3, 32 bits
         prev_kv = false        :: boolean() | 0 | 1 | undefined, % = 4
         ignore_value = false   :: boolean() | 0 | 1 | undefined, % = 5
         ignore_lease = false   :: boolean() | 0 | 1 | undefined % = 6
        }).
-endif.

-ifndef('ETCD.PUTRESPONSE_PB_H').
-define('ETCD.PUTRESPONSE_PB_H', true).
-record('Etcd.PutResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         prev_kv = undefined    :: router_pb:'mvccpb.KeyValue'() | undefined % = 2
        }).
-endif.

-ifndef('ETCD.DELETERANGEREQUEST_PB_H').
-define('ETCD.DELETERANGEREQUEST_PB_H', true).
-record('Etcd.DeleteRangeRequest',
        {key = <<>>             :: iodata() | undefined, % = 1
         range_end = <<>>       :: iodata() | undefined, % = 2
         prev_kv = false        :: boolean() | 0 | 1 | undefined % = 3
        }).
-endif.

-ifndef('ETCD.DELETERANGERESPONSE_PB_H').
-define('ETCD.DELETERANGERESPONSE_PB_H', true).
-record('Etcd.DeleteRangeResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         deleted = 0            :: integer() | undefined, % = 2, 32 bits
         prev_kvs = []          :: [router_pb:'mvccpb.KeyValue'()] | undefined % = 3
        }).
-endif.

-ifndef('ETCD.REQUESTOP_PB_H').
-define('ETCD.REQUESTOP_PB_H', true).
-record('Etcd.RequestOp',
        {request                :: {request_range, router_pb:'Etcd.RangeRequest'()} | {request_put, router_pb:'Etcd.PutRequest'()} | {request_delete_range, router_pb:'Etcd.DeleteRangeRequest'()} | {request_txn, router_pb:'Etcd.TxnRequest'()} | undefined % oneof
        }).
-endif.

-ifndef('ETCD.RESPONSEOP_PB_H').
-define('ETCD.RESPONSEOP_PB_H', true).
-record('Etcd.ResponseOp',
        {response               :: {response_range, router_pb:'Etcd.RangeResponse'()} | {response_put, router_pb:'Etcd.PutResponse'()} | {response_delete_range, router_pb:'Etcd.DeleteRangeResponse'()} | {response_txn, router_pb:'Etcd.TxnResponse'()} | undefined % oneof
        }).
-endif.

-ifndef('ETCD.COMPARE_PB_H').
-define('ETCD.COMPARE_PB_H', true).
-record('Etcd.Compare',
        {result = 'EQUAL'       :: 'EQUAL' | 'GREATER' | 'LESS' | 'NOT_EQUAL' | integer() | undefined, % = 1, enum Etcd.Compare.CompareResult
         target = 'VERSION'     :: 'VERSION' | 'CREATE' | 'MOD' | 'VALUE' | 'LEASE' | integer() | undefined, % = 2, enum Etcd.Compare.CompareTarget
         key = <<>>             :: iodata() | undefined, % = 3
         target_union           :: {version, integer()} | {create_revision, integer()} | {mod_revision, integer()} | {value, iodata()} | {lease, integer()} | undefined, % oneof
         range_end = <<>>       :: iodata() | undefined % = 64
        }).
-endif.

-ifndef('ETCD.TXNREQUEST_PB_H').
-define('ETCD.TXNREQUEST_PB_H', true).
-record('Etcd.TxnRequest',
        {compare = []           :: [router_pb:'Etcd.Compare'()] | undefined, % = 1
         success = []           :: [router_pb:'Etcd.RequestOp'()] | undefined, % = 2
         failure = []           :: [router_pb:'Etcd.RequestOp'()] | undefined % = 3
        }).
-endif.

-ifndef('ETCD.TXNRESPONSE_PB_H').
-define('ETCD.TXNRESPONSE_PB_H', true).
-record('Etcd.TxnResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         succeeded = false      :: boolean() | 0 | 1 | undefined, % = 2
         responses = []         :: [router_pb:'Etcd.ResponseOp'()] | undefined % = 3
        }).
-endif.

-ifndef('ETCD.COMPACTIONREQUEST_PB_H').
-define('ETCD.COMPACTIONREQUEST_PB_H', true).
-record('Etcd.CompactionRequest',
        {revision = 0           :: integer() | undefined, % = 1, 32 bits
         physical = false       :: boolean() | 0 | 1 | undefined % = 2
        }).
-endif.

-ifndef('ETCD.COMPACTIONRESPONSE_PB_H').
-define('ETCD.COMPACTIONRESPONSE_PB_H', true).
-record('Etcd.CompactionResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.HASHREQUEST_PB_H').
-define('ETCD.HASHREQUEST_PB_H', true).
-record('Etcd.HashRequest',
        {
        }).
-endif.

-ifndef('ETCD.HASHKVREQUEST_PB_H').
-define('ETCD.HASHKVREQUEST_PB_H', true).
-record('Etcd.HashKVRequest',
        {revision = 0           :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('ETCD.HASHKVRESPONSE_PB_H').
-define('ETCD.HASHKVRESPONSE_PB_H', true).
-record('Etcd.HashKVResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         hash = 0               :: non_neg_integer() | undefined, % = 2, 32 bits
         compact_revision = 0   :: integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('ETCD.HASHRESPONSE_PB_H').
-define('ETCD.HASHRESPONSE_PB_H', true).
-record('Etcd.HashResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         hash = 0               :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('ETCD.SNAPSHOTREQUEST_PB_H').
-define('ETCD.SNAPSHOTREQUEST_PB_H', true).
-record('Etcd.SnapshotRequest',
        {
        }).
-endif.

-ifndef('ETCD.SNAPSHOTRESPONSE_PB_H').
-define('ETCD.SNAPSHOTRESPONSE_PB_H', true).
-record('Etcd.SnapshotResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         remaining_bytes = 0    :: non_neg_integer() | undefined, % = 2, 32 bits
         blob = <<>>            :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('ETCD.WATCHREQUEST_PB_H').
-define('ETCD.WATCHREQUEST_PB_H', true).
-record('Etcd.WatchRequest',
        {request_union          :: {create_request, router_pb:'Etcd.WatchCreateRequest'()} | {cancel_request, router_pb:'Etcd.WatchCancelRequest'()} | {progress_request, router_pb:'Etcd.WatchProgressRequest'()} | undefined % oneof
        }).
-endif.

-ifndef('ETCD.WATCHCREATEREQUEST_PB_H').
-define('ETCD.WATCHCREATEREQUEST_PB_H', true).
-record('Etcd.WatchCreateRequest',
        {key = <<>>             :: iodata() | undefined, % = 1
         range_end = <<>>       :: iodata() | undefined, % = 2
         start_revision = 0     :: integer() | undefined, % = 3, 32 bits
         progress_notify = false :: boolean() | 0 | 1 | undefined, % = 4
         filters = []           :: ['NOPUT' | 'NODELETE' | integer()] | undefined, % = 5, enum Etcd.WatchCreateRequest.FilterType
         prev_kv = false        :: boolean() | 0 | 1 | undefined, % = 6
         watch_id = 0           :: integer() | undefined, % = 7, 32 bits
         fragment = false       :: boolean() | 0 | 1 | undefined % = 8
        }).
-endif.

-ifndef('ETCD.WATCHCANCELREQUEST_PB_H').
-define('ETCD.WATCHCANCELREQUEST_PB_H', true).
-record('Etcd.WatchCancelRequest',
        {watch_id = 0           :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('ETCD.WATCHPROGRESSREQUEST_PB_H').
-define('ETCD.WATCHPROGRESSREQUEST_PB_H', true).
-record('Etcd.WatchProgressRequest',
        {
        }).
-endif.

-ifndef('ETCD.WATCHRESPONSE_PB_H').
-define('ETCD.WATCHRESPONSE_PB_H', true).
-record('Etcd.WatchResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         watch_id = 0           :: integer() | undefined, % = 2, 32 bits
         created = false        :: boolean() | 0 | 1 | undefined, % = 3
         canceled = false       :: boolean() | 0 | 1 | undefined, % = 4
         compact_revision = 0   :: integer() | undefined, % = 5, 32 bits
         cancel_reason = <<>>   :: iodata() | undefined, % = 6
         fragment = false       :: boolean() | 0 | 1 | undefined, % = 7
         events = []            :: [router_pb:'mvccpb.Event'()] | undefined % = 11
        }).
-endif.

-ifndef('ETCD.LEASEGRANTREQUEST_PB_H').
-define('ETCD.LEASEGRANTREQUEST_PB_H', true).
-record('Etcd.LeaseGrantRequest',
        {'TTL' = 0              :: integer() | undefined, % = 1, 32 bits
         'ID' = 0               :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('ETCD.LEASEGRANTRESPONSE_PB_H').
-define('ETCD.LEASEGRANTRESPONSE_PB_H', true).
-record('Etcd.LeaseGrantResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         'ID' = 0               :: integer() | undefined, % = 2, 32 bits
         'TTL' = 0              :: integer() | undefined, % = 3, 32 bits
         error = <<>>           :: iodata() | undefined % = 4
        }).
-endif.

-ifndef('ETCD.LEASEREVOKEREQUEST_PB_H').
-define('ETCD.LEASEREVOKEREQUEST_PB_H', true).
-record('Etcd.LeaseRevokeRequest',
        {'ID' = 0               :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('ETCD.LEASEREVOKERESPONSE_PB_H').
-define('ETCD.LEASEREVOKERESPONSE_PB_H', true).
-record('Etcd.LeaseRevokeResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.LEASECHECKPOINT_PB_H').
-define('ETCD.LEASECHECKPOINT_PB_H', true).
-record('Etcd.LeaseCheckpoint',
        {'ID' = 0               :: integer() | undefined, % = 1, 32 bits
         remaining_TTL = 0      :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('ETCD.LEASECHECKPOINTREQUEST_PB_H').
-define('ETCD.LEASECHECKPOINTREQUEST_PB_H', true).
-record('Etcd.LeaseCheckpointRequest',
        {checkpoints = []       :: [router_pb:'Etcd.LeaseCheckpoint'()] | undefined % = 1
        }).
-endif.

-ifndef('ETCD.LEASECHECKPOINTRESPONSE_PB_H').
-define('ETCD.LEASECHECKPOINTRESPONSE_PB_H', true).
-record('Etcd.LeaseCheckpointResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.LEASEKEEPALIVEREQUEST_PB_H').
-define('ETCD.LEASEKEEPALIVEREQUEST_PB_H', true).
-record('Etcd.LeaseKeepAliveRequest',
        {'ID' = 0               :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('ETCD.LEASEKEEPALIVERESPONSE_PB_H').
-define('ETCD.LEASEKEEPALIVERESPONSE_PB_H', true).
-record('Etcd.LeaseKeepAliveResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         'ID' = 0               :: integer() | undefined, % = 2, 32 bits
         'TTL' = 0              :: integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('ETCD.LEASETIMETOLIVEREQUEST_PB_H').
-define('ETCD.LEASETIMETOLIVEREQUEST_PB_H', true).
-record('Etcd.LeaseTimeToLiveRequest',
        {'ID' = 0               :: integer() | undefined, % = 1, 32 bits
         keys = false           :: boolean() | 0 | 1 | undefined % = 2
        }).
-endif.

-ifndef('ETCD.LEASETIMETOLIVERESPONSE_PB_H').
-define('ETCD.LEASETIMETOLIVERESPONSE_PB_H', true).
-record('Etcd.LeaseTimeToLiveResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         'ID' = 0               :: integer() | undefined, % = 2, 32 bits
         'TTL' = 0              :: integer() | undefined, % = 3, 32 bits
         grantedTTL = 0         :: integer() | undefined, % = 4, 32 bits
         keys = []              :: [iodata()] | undefined % = 5
        }).
-endif.

-ifndef('ETCD.LEASELEASESREQUEST_PB_H').
-define('ETCD.LEASELEASESREQUEST_PB_H', true).
-record('Etcd.LeaseLeasesRequest',
        {
        }).
-endif.

-ifndef('ETCD.LEASESTATUS_PB_H').
-define('ETCD.LEASESTATUS_PB_H', true).
-record('Etcd.LeaseStatus',
        {'ID' = 0               :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('ETCD.LEASELEASESRESPONSE_PB_H').
-define('ETCD.LEASELEASESRESPONSE_PB_H', true).
-record('Etcd.LeaseLeasesResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         leases = []            :: [router_pb:'Etcd.LeaseStatus'()] | undefined % = 2
        }).
-endif.

-ifndef('ETCD.MEMBER_PB_H').
-define('ETCD.MEMBER_PB_H', true).
-record('Etcd.Member',
        {'ID' = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         name = <<>>            :: iodata() | undefined, % = 2
         peerURLs = []          :: [iodata()] | undefined, % = 3
         clientURLs = []        :: [iodata()] | undefined % = 4
        }).
-endif.

-ifndef('ETCD.MEMBERADDREQUEST_PB_H').
-define('ETCD.MEMBERADDREQUEST_PB_H', true).
-record('Etcd.MemberAddRequest',
        {peerURLs = []          :: [iodata()] | undefined % = 1
        }).
-endif.

-ifndef('ETCD.MEMBERADDRESPONSE_PB_H').
-define('ETCD.MEMBERADDRESPONSE_PB_H', true).
-record('Etcd.MemberAddResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         member = undefined     :: router_pb:'Etcd.Member'() | undefined, % = 2
         members = []           :: [router_pb:'Etcd.Member'()] | undefined % = 3
        }).
-endif.

-ifndef('ETCD.MEMBERREMOVEREQUEST_PB_H').
-define('ETCD.MEMBERREMOVEREQUEST_PB_H', true).
-record('Etcd.MemberRemoveRequest',
        {'ID' = 0               :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('ETCD.MEMBERREMOVERESPONSE_PB_H').
-define('ETCD.MEMBERREMOVERESPONSE_PB_H', true).
-record('Etcd.MemberRemoveResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         members = []           :: [router_pb:'Etcd.Member'()] | undefined % = 2
        }).
-endif.

-ifndef('ETCD.MEMBERUPDATEREQUEST_PB_H').
-define('ETCD.MEMBERUPDATEREQUEST_PB_H', true).
-record('Etcd.MemberUpdateRequest',
        {'ID' = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         peerURLs = []          :: [iodata()] | undefined % = 2
        }).
-endif.

-ifndef('ETCD.MEMBERUPDATERESPONSE_PB_H').
-define('ETCD.MEMBERUPDATERESPONSE_PB_H', true).
-record('Etcd.MemberUpdateResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         members = []           :: [router_pb:'Etcd.Member'()] | undefined % = 2
        }).
-endif.

-ifndef('ETCD.MEMBERLISTREQUEST_PB_H').
-define('ETCD.MEMBERLISTREQUEST_PB_H', true).
-record('Etcd.MemberListRequest',
        {
        }).
-endif.

-ifndef('ETCD.MEMBERLISTRESPONSE_PB_H').
-define('ETCD.MEMBERLISTRESPONSE_PB_H', true).
-record('Etcd.MemberListResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         members = []           :: [router_pb:'Etcd.Member'()] | undefined % = 2
        }).
-endif.

-ifndef('ETCD.DEFRAGMENTREQUEST_PB_H').
-define('ETCD.DEFRAGMENTREQUEST_PB_H', true).
-record('Etcd.DefragmentRequest',
        {
        }).
-endif.

-ifndef('ETCD.DEFRAGMENTRESPONSE_PB_H').
-define('ETCD.DEFRAGMENTRESPONSE_PB_H', true).
-record('Etcd.DefragmentResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.MOVELEADERREQUEST_PB_H').
-define('ETCD.MOVELEADERREQUEST_PB_H', true).
-record('Etcd.MoveLeaderRequest',
        {targetID = 0           :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('ETCD.MOVELEADERRESPONSE_PB_H').
-define('ETCD.MOVELEADERRESPONSE_PB_H', true).
-record('Etcd.MoveLeaderResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.ALARMREQUEST_PB_H').
-define('ETCD.ALARMREQUEST_PB_H', true).
-record('Etcd.AlarmRequest',
        {action = 'GET'         :: 'GET' | 'ACTIVATE' | 'DEACTIVATE' | integer() | undefined, % = 1, enum Etcd.AlarmRequest.AlarmAction
         memberID = 0           :: non_neg_integer() | undefined, % = 2, 32 bits
         alarm = 'NONE'         :: 'NONE' | 'NOSPACE' | 'CORRUPT' | integer() | undefined % = 3, enum Etcd.AlarmType
        }).
-endif.

-ifndef('ETCD.ALARMMEMBER_PB_H').
-define('ETCD.ALARMMEMBER_PB_H', true).
-record('Etcd.AlarmMember',
        {memberID = 0           :: non_neg_integer() | undefined, % = 1, 32 bits
         alarm = 'NONE'         :: 'NONE' | 'NOSPACE' | 'CORRUPT' | integer() | undefined % = 2, enum Etcd.AlarmType
        }).
-endif.

-ifndef('ETCD.ALARMRESPONSE_PB_H').
-define('ETCD.ALARMRESPONSE_PB_H', true).
-record('Etcd.AlarmResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         alarms = []            :: [router_pb:'Etcd.AlarmMember'()] | undefined % = 2
        }).
-endif.

-ifndef('ETCD.STATUSREQUEST_PB_H').
-define('ETCD.STATUSREQUEST_PB_H', true).
-record('Etcd.StatusRequest',
        {
        }).
-endif.

-ifndef('ETCD.STATUSRESPONSE_PB_H').
-define('ETCD.STATUSRESPONSE_PB_H', true).
-record('Etcd.StatusResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         version = <<>>         :: iodata() | undefined, % = 2
         dbSize = 0             :: integer() | undefined, % = 3, 32 bits
         leader = 0             :: non_neg_integer() | undefined, % = 4, 32 bits
         raftIndex = 0          :: non_neg_integer() | undefined, % = 5, 32 bits
         raftTerm = 0           :: non_neg_integer() | undefined, % = 6, 32 bits
         raftAppliedIndex = 0   :: non_neg_integer() | undefined, % = 7, 32 bits
         errors = []            :: [iodata()] | undefined, % = 8
         dbSizeInUse = 0        :: integer() | undefined % = 9, 32 bits
        }).
-endif.

-ifndef('ETCD.AUTHENABLEREQUEST_PB_H').
-define('ETCD.AUTHENABLEREQUEST_PB_H', true).
-record('Etcd.AuthEnableRequest',
        {
        }).
-endif.

-ifndef('ETCD.AUTHDISABLEREQUEST_PB_H').
-define('ETCD.AUTHDISABLEREQUEST_PB_H', true).
-record('Etcd.AuthDisableRequest',
        {
        }).
-endif.

-ifndef('ETCD.AUTHENTICATEREQUEST_PB_H').
-define('ETCD.AUTHENTICATEREQUEST_PB_H', true).
-record('Etcd.AuthenticateRequest',
        {name = <<>>            :: iodata() | undefined, % = 1
         password = <<>>        :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('ETCD.AUTHUSERADDREQUEST_PB_H').
-define('ETCD.AUTHUSERADDREQUEST_PB_H', true).
-record('Etcd.AuthUserAddRequest',
        {name = <<>>            :: iodata() | undefined, % = 1
         password = <<>>        :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('ETCD.AUTHUSERGETREQUEST_PB_H').
-define('ETCD.AUTHUSERGETREQUEST_PB_H', true).
-record('Etcd.AuthUserGetRequest',
        {name = <<>>            :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHUSERDELETEREQUEST_PB_H').
-define('ETCD.AUTHUSERDELETEREQUEST_PB_H', true).
-record('Etcd.AuthUserDeleteRequest',
        {name = <<>>            :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHUSERCHANGEPASSWORDREQUEST_PB_H').
-define('ETCD.AUTHUSERCHANGEPASSWORDREQUEST_PB_H', true).
-record('Etcd.AuthUserChangePasswordRequest',
        {name = <<>>            :: iodata() | undefined, % = 1
         password = <<>>        :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('ETCD.AUTHUSERGRANTROLEREQUEST_PB_H').
-define('ETCD.AUTHUSERGRANTROLEREQUEST_PB_H', true).
-record('Etcd.AuthUserGrantRoleRequest',
        {user = <<>>            :: iodata() | undefined, % = 1
         role = <<>>            :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('ETCD.AUTHUSERREVOKEROLEREQUEST_PB_H').
-define('ETCD.AUTHUSERREVOKEROLEREQUEST_PB_H', true).
-record('Etcd.AuthUserRevokeRoleRequest',
        {name = <<>>            :: iodata() | undefined, % = 1
         role = <<>>            :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('ETCD.AUTHROLEADDREQUEST_PB_H').
-define('ETCD.AUTHROLEADDREQUEST_PB_H', true).
-record('Etcd.AuthRoleAddRequest',
        {name = <<>>            :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHROLEGETREQUEST_PB_H').
-define('ETCD.AUTHROLEGETREQUEST_PB_H', true).
-record('Etcd.AuthRoleGetRequest',
        {role = <<>>            :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHUSERLISTREQUEST_PB_H').
-define('ETCD.AUTHUSERLISTREQUEST_PB_H', true).
-record('Etcd.AuthUserListRequest',
        {
        }).
-endif.

-ifndef('ETCD.AUTHROLELISTREQUEST_PB_H').
-define('ETCD.AUTHROLELISTREQUEST_PB_H', true).
-record('Etcd.AuthRoleListRequest',
        {
        }).
-endif.

-ifndef('ETCD.AUTHROLEDELETEREQUEST_PB_H').
-define('ETCD.AUTHROLEDELETEREQUEST_PB_H', true).
-record('Etcd.AuthRoleDeleteRequest',
        {role = <<>>            :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHROLEGRANTPERMISSIONREQUEST_PB_H').
-define('ETCD.AUTHROLEGRANTPERMISSIONREQUEST_PB_H', true).
-record('Etcd.AuthRoleGrantPermissionRequest',
        {name = <<>>            :: iodata() | undefined, % = 1
         perm = undefined       :: router_pb:'authpb.Permission'() | undefined % = 2
        }).
-endif.

-ifndef('ETCD.AUTHROLEREVOKEPERMISSIONREQUEST_PB_H').
-define('ETCD.AUTHROLEREVOKEPERMISSIONREQUEST_PB_H', true).
-record('Etcd.AuthRoleRevokePermissionRequest',
        {role = <<>>            :: iodata() | undefined, % = 1
         key = <<>>             :: iodata() | undefined, % = 2
         range_end = <<>>       :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('ETCD.AUTHENABLERESPONSE_PB_H').
-define('ETCD.AUTHENABLERESPONSE_PB_H', true).
-record('Etcd.AuthEnableResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHDISABLERESPONSE_PB_H').
-define('ETCD.AUTHDISABLERESPONSE_PB_H', true).
-record('Etcd.AuthDisableResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHENTICATERESPONSE_PB_H').
-define('ETCD.AUTHENTICATERESPONSE_PB_H', true).
-record('Etcd.AuthenticateResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         token = <<>>           :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('ETCD.AUTHUSERADDRESPONSE_PB_H').
-define('ETCD.AUTHUSERADDRESPONSE_PB_H', true).
-record('Etcd.AuthUserAddResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHUSERGETRESPONSE_PB_H').
-define('ETCD.AUTHUSERGETRESPONSE_PB_H', true).
-record('Etcd.AuthUserGetResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         roles = []             :: [iodata()] | undefined % = 2
        }).
-endif.

-ifndef('ETCD.AUTHUSERDELETERESPONSE_PB_H').
-define('ETCD.AUTHUSERDELETERESPONSE_PB_H', true).
-record('Etcd.AuthUserDeleteResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHUSERCHANGEPASSWORDRESPONSE_PB_H').
-define('ETCD.AUTHUSERCHANGEPASSWORDRESPONSE_PB_H', true).
-record('Etcd.AuthUserChangePasswordResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHUSERGRANTROLERESPONSE_PB_H').
-define('ETCD.AUTHUSERGRANTROLERESPONSE_PB_H', true).
-record('Etcd.AuthUserGrantRoleResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHUSERREVOKEROLERESPONSE_PB_H').
-define('ETCD.AUTHUSERREVOKEROLERESPONSE_PB_H', true).
-record('Etcd.AuthUserRevokeRoleResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHROLEADDRESPONSE_PB_H').
-define('ETCD.AUTHROLEADDRESPONSE_PB_H', true).
-record('Etcd.AuthRoleAddResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHROLEGETRESPONSE_PB_H').
-define('ETCD.AUTHROLEGETRESPONSE_PB_H', true).
-record('Etcd.AuthRoleGetResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         perm = []              :: [router_pb:'authpb.Permission'()] | undefined % = 2
        }).
-endif.

-ifndef('ETCD.AUTHROLELISTRESPONSE_PB_H').
-define('ETCD.AUTHROLELISTRESPONSE_PB_H', true).
-record('Etcd.AuthRoleListResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         roles = []             :: [iodata()] | undefined % = 2
        }).
-endif.

-ifndef('ETCD.AUTHUSERLISTRESPONSE_PB_H').
-define('ETCD.AUTHUSERLISTRESPONSE_PB_H', true).
-record('Etcd.AuthUserListResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined, % = 1
         users = []             :: [iodata()] | undefined % = 2
        }).
-endif.

-ifndef('ETCD.AUTHROLEDELETERESPONSE_PB_H').
-define('ETCD.AUTHROLEDELETERESPONSE_PB_H', true).
-record('Etcd.AuthRoleDeleteResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHROLEGRANTPERMISSIONRESPONSE_PB_H').
-define('ETCD.AUTHROLEGRANTPERMISSIONRESPONSE_PB_H', true).
-record('Etcd.AuthRoleGrantPermissionResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('ETCD.AUTHROLEREVOKEPERMISSIONRESPONSE_PB_H').
-define('ETCD.AUTHROLEREVOKEPERMISSIONRESPONSE_PB_H', true).
-record('Etcd.AuthRoleRevokePermissionResponse',
        {header = undefined     :: router_pb:'Etcd.ResponseHeader'() | undefined % = 1
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.FILEDESCRIPTORSET_PB_H').
-define('GOOGLE.PROTOBUF.FILEDESCRIPTORSET_PB_H', true).
-record('google.protobuf.FileDescriptorSet',
        {file = []              :: [router_pb:'google.protobuf.FileDescriptorProto'()] | undefined % = 1
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.FILEDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.FILEDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.FileDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         package                :: iodata() | undefined, % = 2
         dependency = []        :: [iodata()] | undefined, % = 3
         public_dependency = [] :: [integer()] | undefined, % = 10, 32 bits
         weak_dependency = []   :: [integer()] | undefined, % = 11, 32 bits
         message_type = []      :: [router_pb:'google.protobuf.DescriptorProto'()] | undefined, % = 4
         enum_type = []         :: [router_pb:'google.protobuf.EnumDescriptorProto'()] | undefined, % = 5
         service = []           :: [router_pb:'google.protobuf.ServiceDescriptorProto'()] | undefined, % = 6
         extension = []         :: [router_pb:'google.protobuf.FieldDescriptorProto'()] | undefined, % = 7
         options                :: router_pb:'google.protobuf.FileOptions'() | undefined, % = 8
         source_code_info       :: router_pb:'google.protobuf.SourceCodeInfo'() | undefined, % = 9
         syntax                 :: iodata() | undefined % = 12
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.DESCRIPTORPROTO.EXTENSIONRANGE_PB_H').
-define('GOOGLE.PROTOBUF.DESCRIPTORPROTO.EXTENSIONRANGE_PB_H', true).
-record('google.protobuf.DescriptorProto.ExtensionRange',
        {start                  :: integer() | undefined, % = 1, 32 bits
         'end'                  :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.DESCRIPTORPROTO.RESERVEDRANGE_PB_H').
-define('GOOGLE.PROTOBUF.DESCRIPTORPROTO.RESERVEDRANGE_PB_H', true).
-record('google.protobuf.DescriptorProto.ReservedRange',
        {start                  :: integer() | undefined, % = 1, 32 bits
         'end'                  :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.DESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.DESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.DescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         field = []             :: [router_pb:'google.protobuf.FieldDescriptorProto'()] | undefined, % = 2
         extension = []         :: [router_pb:'google.protobuf.FieldDescriptorProto'()] | undefined, % = 6
         nested_type = []       :: [router_pb:'google.protobuf.DescriptorProto'()] | undefined, % = 3
         enum_type = []         :: [router_pb:'google.protobuf.EnumDescriptorProto'()] | undefined, % = 4
         extension_range = []   :: [router_pb:'google.protobuf.DescriptorProto.ExtensionRange'()] | undefined, % = 5
         oneof_decl = []        :: [router_pb:'google.protobuf.OneofDescriptorProto'()] | undefined, % = 8
         options                :: router_pb:'google.protobuf.MessageOptions'() | undefined, % = 7
         reserved_range = []    :: [router_pb:'google.protobuf.DescriptorProto.ReservedRange'()] | undefined, % = 9
         reserved_name = []     :: [iodata()] | undefined % = 10
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.FIELDDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.FIELDDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.FieldDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         number                 :: integer() | undefined, % = 3, 32 bits
         label                  :: 'LABEL_OPTIONAL' | 'LABEL_REQUIRED' | 'LABEL_REPEATED' | integer() | undefined, % = 4, enum google.protobuf.FieldDescriptorProto.Label
         type                   :: 'TYPE_DOUBLE' | 'TYPE_FLOAT' | 'TYPE_INT64' | 'TYPE_UINT64' | 'TYPE_INT32' | 'TYPE_FIXED64' | 'TYPE_FIXED32' | 'TYPE_BOOL' | 'TYPE_STRING' | 'TYPE_GROUP' | 'TYPE_MESSAGE' | 'TYPE_BYTES' | 'TYPE_UINT32' | 'TYPE_ENUM' | 'TYPE_SFIXED32' | 'TYPE_SFIXED64' | 'TYPE_SINT32' | 'TYPE_SINT64' | integer() | undefined, % = 5, enum google.protobuf.FieldDescriptorProto.Type
         type_name              :: iodata() | undefined, % = 6
         extendee               :: iodata() | undefined, % = 2
         default_value          :: iodata() | undefined, % = 7
         oneof_index            :: integer() | undefined, % = 9, 32 bits
         json_name              :: iodata() | undefined, % = 10
         options                :: router_pb:'google.protobuf.FieldOptions'() | undefined % = 8
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ONEOFDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.ONEOFDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.OneofDescriptorProto',
        {name                   :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ENUMDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.ENUMDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.EnumDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         value = []             :: [router_pb:'google.protobuf.EnumValueDescriptorProto'()] | undefined, % = 2
         options                :: router_pb:'google.protobuf.EnumOptions'() | undefined % = 3
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ENUMVALUEDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.ENUMVALUEDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.EnumValueDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         number                 :: integer() | undefined, % = 2, 32 bits
         options                :: router_pb:'google.protobuf.EnumValueOptions'() | undefined % = 3
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.SERVICEDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.SERVICEDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.ServiceDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         method = []            :: [router_pb:'google.protobuf.MethodDescriptorProto'()] | undefined, % = 2
         options                :: router_pb:'google.protobuf.ServiceOptions'() | undefined % = 3
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.METHODDESCRIPTORPROTO_PB_H').
-define('GOOGLE.PROTOBUF.METHODDESCRIPTORPROTO_PB_H', true).
-record('google.protobuf.MethodDescriptorProto',
        {name                   :: iodata() | undefined, % = 1
         input_type             :: iodata() | undefined, % = 2
         output_type            :: iodata() | undefined, % = 3
         options                :: router_pb:'google.protobuf.MethodOptions'() | undefined, % = 4
         client_streaming = false :: boolean() | 0 | 1 | undefined, % = 5
         server_streaming = false :: boolean() | 0 | 1 | undefined % = 6
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.FILEOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.FILEOPTIONS_PB_H', true).
-record('google.protobuf.FileOptions',
        {java_package           :: iodata() | undefined, % = 1
         java_outer_classname   :: iodata() | undefined, % = 8
         java_multiple_files = false :: boolean() | 0 | 1 | undefined, % = 10
         java_generate_equals_and_hash = false :: boolean() | 0 | 1 | undefined, % = 20
         java_string_check_utf8 = false :: boolean() | 0 | 1 | undefined, % = 27
         optimize_for = 'SPEED' :: 'SPEED' | 'CODE_SIZE' | 'LITE_RUNTIME' | integer() | undefined, % = 9, enum google.protobuf.FileOptions.OptimizeMode
         go_package             :: iodata() | undefined, % = 11
         cc_generic_services = false :: boolean() | 0 | 1 | undefined, % = 16
         java_generic_services = false :: boolean() | 0 | 1 | undefined, % = 17
         py_generic_services = false :: boolean() | 0 | 1 | undefined, % = 18
         deprecated = false     :: boolean() | 0 | 1 | undefined, % = 23
         cc_enable_arenas = false :: boolean() | 0 | 1 | undefined, % = 31
         objc_class_prefix      :: iodata() | undefined, % = 36
         csharp_namespace       :: iodata() | undefined, % = 37
         javanano_use_deprecated_package :: boolean() | 0 | 1 | undefined, % = 38
         uninterpreted_option = [] :: [router_pb:'google.protobuf.UninterpretedOption'()] | undefined, % = 999
         goproto_getters_all    :: boolean() | 0 | 1 | undefined, % = 63001
         goproto_enum_prefix_all :: boolean() | 0 | 1 | undefined, % = 63002
         goproto_stringer_all   :: boolean() | 0 | 1 | undefined, % = 63003
         verbose_equal_all      :: boolean() | 0 | 1 | undefined, % = 63004
         face_all               :: boolean() | 0 | 1 | undefined, % = 63005
         gostring_all           :: boolean() | 0 | 1 | undefined, % = 63006
         populate_all           :: boolean() | 0 | 1 | undefined, % = 63007
         stringer_all           :: boolean() | 0 | 1 | undefined, % = 63008
         onlyone_all            :: boolean() | 0 | 1 | undefined, % = 63009
         equal_all              :: boolean() | 0 | 1 | undefined, % = 63013
         description_all        :: boolean() | 0 | 1 | undefined, % = 63014
         testgen_all            :: boolean() | 0 | 1 | undefined, % = 63015
         benchgen_all           :: boolean() | 0 | 1 | undefined, % = 63016
         marshaler_all          :: boolean() | 0 | 1 | undefined, % = 63017
         unmarshaler_all        :: boolean() | 0 | 1 | undefined, % = 63018
         stable_marshaler_all   :: boolean() | 0 | 1 | undefined, % = 63019
         sizer_all              :: boolean() | 0 | 1 | undefined, % = 63020
         goproto_enum_stringer_all :: boolean() | 0 | 1 | undefined, % = 63021
         enum_stringer_all      :: boolean() | 0 | 1 | undefined, % = 63022
         unsafe_marshaler_all   :: boolean() | 0 | 1 | undefined, % = 63023
         unsafe_unmarshaler_all :: boolean() | 0 | 1 | undefined, % = 63024
         goproto_extensions_map_all :: boolean() | 0 | 1 | undefined, % = 63025
         goproto_unrecognized_all :: boolean() | 0 | 1 | undefined, % = 63026
         gogoproto_import       :: boolean() | 0 | 1 | undefined, % = 63027
         protosizer_all         :: boolean() | 0 | 1 | undefined, % = 63028
         compare_all            :: boolean() | 0 | 1 | undefined % = 63029
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.MESSAGEOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.MESSAGEOPTIONS_PB_H', true).
-record('google.protobuf.MessageOptions',
        {message_set_wire_format = false :: boolean() | 0 | 1 | undefined, % = 1
         no_standard_descriptor_accessor = false :: boolean() | 0 | 1 | undefined, % = 2
         deprecated = false     :: boolean() | 0 | 1 | undefined, % = 3
         map_entry              :: boolean() | 0 | 1 | undefined, % = 7
         uninterpreted_option = [] :: [router_pb:'google.protobuf.UninterpretedOption'()] | undefined, % = 999
         goproto_getters        :: boolean() | 0 | 1 | undefined, % = 64001
         goproto_stringer       :: boolean() | 0 | 1 | undefined, % = 64003
         verbose_equal          :: boolean() | 0 | 1 | undefined, % = 64004
         face                   :: boolean() | 0 | 1 | undefined, % = 64005
         gostring               :: boolean() | 0 | 1 | undefined, % = 64006
         populate               :: boolean() | 0 | 1 | undefined, % = 64007
         stringer               :: boolean() | 0 | 1 | undefined, % = 67008
         onlyone                :: boolean() | 0 | 1 | undefined, % = 64009
         equal                  :: boolean() | 0 | 1 | undefined, % = 64013
         description            :: boolean() | 0 | 1 | undefined, % = 64014
         testgen                :: boolean() | 0 | 1 | undefined, % = 64015
         benchgen               :: boolean() | 0 | 1 | undefined, % = 64016
         marshaler              :: boolean() | 0 | 1 | undefined, % = 64017
         unmarshaler            :: boolean() | 0 | 1 | undefined, % = 64018
         stable_marshaler       :: boolean() | 0 | 1 | undefined, % = 64019
         sizer                  :: boolean() | 0 | 1 | undefined, % = 64020
         unsafe_marshaler       :: boolean() | 0 | 1 | undefined, % = 64023
         unsafe_unmarshaler     :: boolean() | 0 | 1 | undefined, % = 64024
         goproto_extensions_map :: boolean() | 0 | 1 | undefined, % = 64025
         goproto_unrecognized   :: boolean() | 0 | 1 | undefined, % = 64026
         protosizer             :: boolean() | 0 | 1 | undefined, % = 64028
         compare                :: boolean() | 0 | 1 | undefined % = 64029
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.FIELDOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.FIELDOPTIONS_PB_H', true).
-record('google.protobuf.FieldOptions',
        {ctype = 'STRING'       :: 'STRING' | 'CORD' | 'STRING_PIECE' | integer() | undefined, % = 1, enum google.protobuf.FieldOptions.CType
         packed                 :: boolean() | 0 | 1 | undefined, % = 2
         jstype = 'JS_NORMAL'   :: 'JS_NORMAL' | 'JS_STRING' | 'JS_NUMBER' | integer() | undefined, % = 6, enum google.protobuf.FieldOptions.JSType
         lazy = false           :: boolean() | 0 | 1 | undefined, % = 5
         deprecated = false     :: boolean() | 0 | 1 | undefined, % = 3
         weak = false           :: boolean() | 0 | 1 | undefined, % = 10
         uninterpreted_option = [] :: [router_pb:'google.protobuf.UninterpretedOption'()] | undefined, % = 999
         nullable               :: boolean() | 0 | 1 | undefined, % = 65001
         embed                  :: boolean() | 0 | 1 | undefined, % = 65002
         customtype             :: iodata() | undefined, % = 65003
         customname             :: iodata() | undefined, % = 65004
         jsontag                :: iodata() | undefined, % = 65005
         moretags               :: iodata() | undefined, % = 65006
         casttype               :: iodata() | undefined, % = 65007
         castkey                :: iodata() | undefined, % = 65008
         castvalue              :: iodata() | undefined, % = 65009
         stdtime                :: boolean() | 0 | 1 | undefined, % = 65010
         stdduration            :: boolean() | 0 | 1 | undefined % = 65011
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ENUMOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.ENUMOPTIONS_PB_H', true).
-record('google.protobuf.EnumOptions',
        {allow_alias            :: boolean() | 0 | 1 | undefined, % = 2
         deprecated = false     :: boolean() | 0 | 1 | undefined, % = 3
         uninterpreted_option = [] :: [router_pb:'google.protobuf.UninterpretedOption'()] | undefined, % = 999
         goproto_enum_prefix    :: boolean() | 0 | 1 | undefined, % = 62001
         goproto_enum_stringer  :: boolean() | 0 | 1 | undefined, % = 62021
         enum_stringer          :: boolean() | 0 | 1 | undefined, % = 62022
         enum_customname        :: iodata() | undefined % = 62023
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ENUMVALUEOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.ENUMVALUEOPTIONS_PB_H', true).
-record('google.protobuf.EnumValueOptions',
        {deprecated = false     :: boolean() | 0 | 1 | undefined, % = 1
         uninterpreted_option = [] :: [router_pb:'google.protobuf.UninterpretedOption'()] | undefined, % = 999
         enumvalue_customname   :: iodata() | undefined % = 66001
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.SERVICEOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.SERVICEOPTIONS_PB_H', true).
-record('google.protobuf.ServiceOptions',
        {deprecated = false     :: boolean() | 0 | 1 | undefined, % = 33
         uninterpreted_option = [] :: [router_pb:'google.protobuf.UninterpretedOption'()] | undefined % = 999
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.METHODOPTIONS_PB_H').
-define('GOOGLE.PROTOBUF.METHODOPTIONS_PB_H', true).
-record('google.protobuf.MethodOptions',
        {deprecated = false     :: boolean() | 0 | 1 | undefined, % = 33
         uninterpreted_option = [] :: [router_pb:'google.protobuf.UninterpretedOption'()] | undefined % = 999
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.UNINTERPRETEDOPTION.NAMEPART_PB_H').
-define('GOOGLE.PROTOBUF.UNINTERPRETEDOPTION.NAMEPART_PB_H', true).
-record('google.protobuf.UninterpretedOption.NamePart',
        {name_part              :: iodata(),        % = 1
         is_extension           :: boolean() | 0 | 1 % = 2
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.UNINTERPRETEDOPTION_PB_H').
-define('GOOGLE.PROTOBUF.UNINTERPRETEDOPTION_PB_H', true).
-record('google.protobuf.UninterpretedOption',
        {name = []              :: [router_pb:'google.protobuf.UninterpretedOption.NamePart'()] | undefined, % = 2
         identifier_value       :: iodata() | undefined, % = 3
         positive_int_value     :: non_neg_integer() | undefined, % = 4, 32 bits
         negative_int_value     :: integer() | undefined, % = 5, 32 bits
         double_value           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 6
         string_value           :: iodata() | undefined, % = 7
         aggregate_value        :: iodata() | undefined % = 8
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.SOURCECODEINFO.LOCATION_PB_H').
-define('GOOGLE.PROTOBUF.SOURCECODEINFO.LOCATION_PB_H', true).
-record('google.protobuf.SourceCodeInfo.Location',
        {path = []              :: [integer()] | undefined, % = 1, 32 bits
         span = []              :: [integer()] | undefined, % = 2, 32 bits
         leading_comments       :: iodata() | undefined, % = 3
         trailing_comments      :: iodata() | undefined, % = 4
         leading_detached_comments = [] :: [iodata()] | undefined % = 6
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.SOURCECODEINFO_PB_H').
-define('GOOGLE.PROTOBUF.SOURCECODEINFO_PB_H', true).
-record('google.protobuf.SourceCodeInfo',
        {location = []          :: [router_pb:'google.protobuf.SourceCodeInfo.Location'()] | undefined % = 1
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.GENERATEDCODEINFO.ANNOTATION_PB_H').
-define('GOOGLE.PROTOBUF.GENERATEDCODEINFO.ANNOTATION_PB_H', true).
-record('google.protobuf.GeneratedCodeInfo.Annotation',
        {path = []              :: [integer()] | undefined, % = 1, 32 bits
         source_file            :: iodata() | undefined, % = 2
         'begin'                :: integer() | undefined, % = 3, 32 bits
         'end'                  :: integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.GENERATEDCODEINFO_PB_H').
-define('GOOGLE.PROTOBUF.GENERATEDCODEINFO_PB_H', true).
-record('google.protobuf.GeneratedCodeInfo',
        {annotation = []        :: [router_pb:'google.protobuf.GeneratedCodeInfo.Annotation'()] | undefined % = 1
        }).
-endif.

-ifndef('MVCCPB.KEYVALUE_PB_H').
-define('MVCCPB.KEYVALUE_PB_H', true).
-record('mvccpb.KeyValue',
        {key = <<>>             :: iodata() | undefined, % = 1
         create_revision = 0    :: integer() | undefined, % = 2, 32 bits
         mod_revision = 0       :: integer() | undefined, % = 3, 32 bits
         version = 0            :: integer() | undefined, % = 4, 32 bits
         value = <<>>           :: iodata() | undefined, % = 5
         lease = 0              :: integer() | undefined % = 6, 32 bits
        }).
-endif.

-ifndef('MVCCPB.EVENT_PB_H').
-define('MVCCPB.EVENT_PB_H', true).
-record('mvccpb.Event',
        {type = 'PUT'           :: 'PUT' | 'DELETE' | integer() | undefined, % = 1, enum mvccpb.Event.EventType
         kv = undefined         :: router_pb:'mvccpb.KeyValue'() | undefined, % = 2
         prev_kv = undefined    :: router_pb:'mvccpb.KeyValue'() | undefined % = 3
        }).
-endif.

-ifndef('AUTHPB.USER_PB_H').
-define('AUTHPB.USER_PB_H', true).
-record('authpb.User',
        {name = <<>>            :: iodata() | undefined, % = 1
         password = <<>>        :: iodata() | undefined, % = 2
         roles = []             :: [iodata()] | undefined % = 3
        }).
-endif.

-ifndef('AUTHPB.PERMISSION_PB_H').
-define('AUTHPB.PERMISSION_PB_H', true).
-record('authpb.Permission',
        {permType = 'READ'      :: 'READ' | 'WRITE' | 'READWRITE' | integer() | undefined, % = 1, enum authpb.Permission.Type
         key = <<>>             :: iodata() | undefined, % = 2
         range_end = <<>>       :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('AUTHPB.ROLE_PB_H').
-define('AUTHPB.ROLE_PB_H', true).
-record('authpb.Role',
        {name = <<>>            :: iodata() | undefined, % = 1
         keyPermission = []     :: [router_pb:'authpb.Permission'()] | undefined % = 2
        }).
-endif.

-endif.
