name: eetcd CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Install Etcd
      run: ./setup_etcd.sh
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 ct
